name: Deploy to AWS EC2
env:
  SERVER_USER: ec2-user  # Default user for Amazon Linux or Ubuntu EC2
  SERVER_IP: ${{ secrets.AWS_EC2_IP }}  # Public IP of your EC2 instance
  PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}  # Private key for SSH
run: |
  echo "${{ secrets.AWS_PRIVATE_KEY }}" > private_key.pem
  chmod 600 private_key.pem
  ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
  docker pull <your-dockerhub-username>/flask_app:latest
  docker stop flask_app || true
  docker rm flask_app || true
  docker run -d --rm -p 80:5000 --name flask_app <your-dockerhub-username>/flask_app:latest
  EOF
  rm -f private_key.pem
