name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
<<<<<<< HEAD
          username: "atef2178"  # Replace with your actual DockerHub username
          password: "dckr_pat_CD9WWgq5rs2TlqsZpiDU5REbIqI"  # Replace with your actual DockerHub password or token
=======
          username: ${{ secrets.ATEF2178 }}
          password: ${{ secrets.ATEF2178 }}
>>>>>>> 9ad25f8da651a130ffed97916e38c8198335c393

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: your_dockerhub_username/flask_app:latest  # Replace with your actual DockerHub username and repository name

      # Step 5: Deploy to server (Optional)
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no username@server_ip << EOF
          docker pull your_dockerhub_username/flask_app:latest  # Replace with your DockerHub username and repository name
          docker stop flask_app || true
          docker run -d --rm -p 80:5000 --name flask_app your_dockerhub_username/flask_app:latest  # Replace with your DockerHub username and repository name
          EOF
