name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and push Docker image to public DockerHub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: atef2178/flask_app:latest
          build-args: --progress=plain

      # Step 4: Deploy to server
      - name: Deploy to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
          docker pull atef2178/flask_app:latest
          docker stop flask_app || true
          docker rm flask_app || true
          docker run -d --rm -p 80:5000 --name flask_app atef2178/flask_app:latest
          EOF
